# Generated by Django 5.2.1 on 2025-05-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_friend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='Friends',
        ),
    ]
